# Generated by Django 4.2.4 on 2023-09-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotel_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='website',
        ),
    ]
