# Generated by Django 4.2.4 on 2023-10-12 09:23

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hotel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='end_date',
            field=models.DateField(validators=[home.models.validate_not_earlier_than_yesterday]),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='start_date',
            field=models.DateField(validators=[home.models.validate_not_earlier_than_yesterday]),
        ),
    ]
